contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - ca-certificates-bundle
    - alpine-baselayout-data
    - nginx
    - php8
    - php8-intl
    - php8-xsl
    - php8-amqp
    - php8-gd
    - php8-openssl
    - php8-sodium
    - php8-curl
    - php8-zip
    - php8-pdo_mysql
    - php8-bcmath
    - php8-bz2
    - php8-exif
    - php8-mysqli
    - php8-fpm
# APCu || OPCache : OPCache by default
#    - php8-apcu
    - php8-opcache

entrypoint:
  type: service-bundle
  services:
    nginx: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    php-fpm: /usr/local/sbin/php8-fpm

accounts:
  groups:
    - groupname: www-data
      gid: 1000
  users:
    - username: www-data
      uid: 1000
  run-as: www-data

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

paths:
  - path: /run/nginx
    type: directory
    uid: 1000
    gid: 1000
    permissions: 0o755
  - path: /etc/nginx/http.d/default.conf
    type: hardlink
    source: /usr/share/nginx/http-default_server.conf
    uid: 1000
    gid: 1000
    permissions: 0o644

archs:
  - arm64
  - amd64