contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - ca-certificates-bundle
    - alpine-baselayout-data
    - php81
    - php81-intl
    - php81-xsl
    - php81-pecl-amqp
    - php81-gd
    - php81-openssl
    - php81-sodium
    - php81-curl
    - php81-zip
    - php81-pdo_mysql
    - php81-bcmath
    - php81-bz2
    - php81-exif
    - php81-mysqli
# APCu || OPCache : OPCache by default
#    - php81-pecl-apcu
    - php81-opcache

entrypoint:
  type: service-bundle
  services:
    php: /usr/bin/php81

accounts:
  groups:
    - groupname: www-data
      gid: 1000
  users:
    - username: www-data
      uid: 1000

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

archs:
  - arm64
  - amd64