contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - ca-certificates-bundle
    - alpine-baselayout-data
    - nginx
    - php81
    - php81-intl
    - php81-xml
    - php81-xsl
    - php81-pecl-amqp
    - php81-gd
    - php81-openssl
    - php81-sodium
    - php81-curl
    - php81-zip
    - php81-pdo_mysql
    - php81-bcmath
    - php81-bz2
    - php81-exif
    - php81-mysqli
    - php81-fpm
    - php81-ctype
    - php81-tokenizer
    - php81-session
# APCu || OPCache : OPCache by default
#    - php81-pecl-apcu
    - php81-opcache
    - php81-fileinfo
    - php81-simplexml

entrypoint:
  type: service-bundle
  services:
    nginx: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    php-fpm81: /usr/sbin/php-fpm81 -F -R

accounts:
  groups:
    - groupname: www-data
      gid: 1000
  users:
    - username: www-data
      uid: 1000

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

paths:
  - path: /run/nginx
    type: directory
    uid: 1000
    gid: 1000
    permissions: 0o755
  - path: /etc/nginx/http.d/default.conf
    type: hardlink
    source: /usr/share/nginx/http-default_server.conf
    uid: 1000
    gid: 1000
    permissions: 0o644
  - path: /usr/sbin/php
    type: hardlink
    source: /usr/bin/php81
    permissions: 0o755

archs:
  - arm64
  - amd64